### PR TITLE
[WIP] AVFoundation video input/output objects for macOS

### PR DESCRIPTION
**Pull request by danomatika**
Preliminary work towards video input & output objects using the AVFoundation framework on macOS as QuickTime has been deprecated since 10.7 and removed in 10.12.

Required objects:

* [ ] filmAVFoundation
* [ ] videoAVFoundation
* [ ] recordAVFoundation
* [ ] imageAVFoundation(?)

If you want to build and test the work in this branch, you can clone via:

    git clone https://github.com/danomatika/Gem.git -b avfoundation 

UPDATE: Using [this guide](https://github.com/umlaeute/Gem/wiki/How-to-build-Gem-on-macOS-Sierra-%2810.12%29) as a start, here's the minimal steps to build this branch on 10.12:

Set up build environment:

    brew install pkg-config automaker libtool
    brew install imagemagick
    brew install gettext
    brew link --force gettext

_Note: If you're afraid of the forced gettext linking, simply unlink after you've configured GEM via: `brew unlink gettext`_

Configure by disabling quicktime and setting path to Pd:

    ./configure --without-QuickTime-framework --without-lqt \
    --without-libquicktime --enable-fat-binary=i386 --without-ftgl \
    --with-imagemagick --with-pd=/Applications/Pd-0.48-0/Contents/Resources

Build, use -j 10 for parallel build to speed things up:

    make -j 10

Even with a parallel build, it will take *a while* the first time you build GEM. After that, you only rebuild the bits that are being worked on, so its much quicker and you can just run a normal `make`.

The best way to test things is to place a test patch in the Gem directory which opens a GEM window and the *AVFoundation objects. Since it's next to the GEM externals, they should load directly without needing to specify the path, etc.

Here's a basic test patch for filmAVFoundation: [test-filmavf.zip](https://github.com/umlaeute/Gem/files/1466932/test-filmavf.zip)

### CODE REVIEW

**Comment by danomatika** [comment]
Current status: filmAVFoundation is working but there is a memory leak and Pd crashes about a minute after playing back video. Also, performance could be improved.

**Comment by megrimm** [comment]
just compiled with error:

AVFMoviePlayer.m:134:5: error: ARC forbids explicit message send of 'release'
    dispatch_release(done);

see:
http://stackoverflow.com/questions/22996437/release-is-unavailable-not-available-in-automatic-reference-counting-mode

compiled for me after commenting out line 129 & 134

**Comment by rnkn** [comment]
Does this mean that video is currently not functional with Gem (and I guess thus Pd) on macOS 10.12?

**Comment by danomatika** [comment]
> Does this mean that video is currently not functional with Gem (and I guess thus Pd) on macOS 10.12?

Yes

**Comment by rnkn** [comment]
Is there anything I can do to help without knowing C/C++?

**Comment by megrimm** [comment]
how can we get this pull request merged with master? i know its not working at moment but it would be easier to just git pull upstream from master in order to have a go at getting this working?

idk... looks like there are conflicting files with the build that I do not quite understand. 

basically how do we move forward with this?

thanks
m

**Comment by danomatika** [comment]
@megrimm Right now we don't. This is only 20% working, at best.

**Comment by megrimm** [comment]
hmmmm... so my git understanding is still quite limited when it comes to more that fetch upstream/master...

what would be the proper way to work on this from a dev perspective? 

if i pull just your avfoundation branch the build fails. recent upstream/master fixes remedy this. i am not sure how to merge these two to my local fork, etc

**Comment by danomatika** [comment]
Fixed. There was a conflict between the master and this branch. Conflicts a

Proper way is:

1. add a remote to the source you want to pull from ie. 

    git remote add gem https://github.com/umlaeute/Gem.git

2. then you can fetch from it

    git fetch gem master

3. then you can merge into the current branch

    git merge gem/master

4. if there are conflicts, they need to be fixed, and then committed to complete the merge

5. push & then make a PR

**Comment by megrimm** [comment]
cool... thanks for the quick tutorial too!

**Comment by danomatika** [comment]
I appear to have fixed the memory leak in filmAVFoundation. Next would be to add handling for the colorspace conversions.

**Comment by danomatika** [comment]
Wait. This is not really done yet. Only the film object is implemented and it's not finished/performative...

**Comment by umlaeute** [comment]
i know that it is not ready yet.
but this mainly means that it shouldn't be built by default (until it is ready).

**Comment by danomatika** [comment]
Closing the PR drops the discussion history when I have to keep opening new PRs. Let's at least reopen it.

**Comment by umlaeute** [comment]
doh. i didn't think that I would actually be closing the PR by merging it.
however, I don't see a way to re-open it, but it's probably enough to just push more commits to it.
(though probably not, as indicated on [stackoverflow](https://stackoverflow.com/questions/12674304/)

**Pull request merged**
