### PR TITLE
Revert rev. ddcfc43 and 307be69 to fix a regression in the QT4L plugin

### LINKED ISSUE #233: QT4L regressions in Gem v0.94
I can reproduce this with Pd 0.49.0, running Gem v0.94 (or current HEAD), on Arch and Ubuntu (19.04), using, e.g., Gem/examples/04.pix/film.pd or any of my own patches utilizing pix_film. (On Ubuntu I first have to remove the gem-plugin-gmerlin package, since otherwise that decoder seems to be used rather than libquicktime to decode most file types.)

The issues are:

* Rev. ddcfc435523efd3bd148f2325235d6d614b8f13b makes Pd lock up hard (Pd becomes completely unresponsive running at 100% cpu,  so that I have to kill it) when reaching the end of the video file after starting playback with the [auto 1( message. Looks like it's trying to read past the last frame and never detects the end of the video, the third outlet of pix_film doesn't get a bang either.

* Rev. 307be698d552e24cb0e7a26bd881582cce83fb8e causes more of a cosmetic issue, namely that either some random junk or nothing at all gets rendered as the first frame after the video file has been loaded.

None of that happened in Gem v0.93. I'm not sure what the proper resolution is, but I can make both issues go away and get the previous behavior by just reverting the revisions above and recompiling the plugin.

### PR DESCRIPTION
**Pull request by agraef**
Fixes #233.

### CODE REVIEW

**Comment by umlaeute** [comment]
nah.

both rev.ddcfc43 and 307be69 had a reason and where actually fixing bugs.
unfortunately they introduced a regression, but that doesn't mean that they should be simply reverted.

**Comment by agraef** [comment]
Yeah, I have to admit that out of desperation I was just tinkering about with the symptoms there. :) Anyway, thanks for deploying a proper fix, works great for me!

**Comment by umlaeute** [comment]
but by curing the symptoms you put me on the right track :-)

and now we also have a fix for https://github.com/umlaeute/Gem/issues/231

so thanks to you :clap:

**Comment by agraef** [comment]
Cool, glad that I could help! :)

I'm going to sync our Gem submodule downstream at the Purr Data project (in fact I already sent Jonathan a PR on that), and I will keep that rolling along with your master branch from now on. So at long last we got Gem 0.94+git (unpatched!) in Purr Data now, I've been working towards that for quite some time now. :)

I'm still fighting with the DS backend on Windows, though, it just refuses to load most common video file types, such as mp4. I have that with both Vanilla and Purr. I need to look into that first, though, before I can submit an issue or PR.

**Comment by agraef** [comment]
@umlaeute I really hate to say it, but while the latest from master works great on both Ubuntu 19.04 and Arch for me, I'm now getting crashes in libavcodec on openSUSE. And once again my crappy attempt at a fix (using https://github.com/agraef/Gem/commit/53e3be2faf3d7d555ddae8f5d97e14449446b1b0) makes those crashes go away completely.

I'm stumped. My first guess was that openSUSE might use an older version of libavcodec and/or libquicktime which behaves differently, but I checked that and I'm using exactly the same versions there as on Arch and Ubuntu 19.04 where everything works fine without any crashes. Of course the openSUSE folks may patch up the ffmpeg and libquicktime sources in different ways, I haven't checked that yet.

Now openSUSE might not be the end-all and be-all of multimedia-centric distros, but video playback works fine in vlc, so it should work fine in Gem, too. And this crash might actually indicate that there's still a one-off bug lurking somewhere in this code. I'm off for vacation next week, but I'll see that I can get a meaningful gdb backtrace and submit another problem report asap, if I can't solve it myself.

**Comment by agraef** [comment]
Well, the backtrace doesn't tell me much:

~~~
#0  0x00007ffff4a2fe6f in avcodec_flush_buffers (avctx=0x555555e9f7c0)
    at libavcodec/decode.c:2029
#1  0x00007ffff57da0b7 in resync_ffmpeg (file=0x555555e83530, track=0)
    at video.c:1183
#2  0x00007ffff6da17b3 in quicktime_set_video_position ()
   from /usr/lib64/libquicktime.so.0
#3  0x00007ffff7fbb952 in gem::plugins::filmQT4L::changeImage(int, int) ()
   from /opt/purr-data/lib/pd-l2ork/extra/Gem/gem_filmQT4L.so
#4  0x00007ffff765272e in pix_film::grabThread(void*) ()
   from /opt/purr-data/lib/pd-l2ork/extra/Gem/Gem.pd_linux
#5  0x00007ffff7e4afaa in start_thread () from /lib64/libpthread.so.0
#6  0x00007ffff7ac373f in clone () from /lib64/libc.so.6
~~~

I've looked at the code, and I can't see any one-offs in there. Still it crashes. Maybe a libavcodec and/or libquicktime bug, that was patched up in Arch and Ubuntu, but not openSUSE? Only guessing there.

The curious thing is that I can make this crash go away with https://github.com/agraef/Gem/commit/53e3be2faf3d7d555ddae8f5d97e14449446b1b0. That seems to indicate that current HEAD exercises some code path in libquicktime and/or libavcodec now that isn't taken in https://github.com/agraef/Gem/commit/53e3be2faf3d7d555ddae8f5d97e14449446b1b0. I guess I'll have to look at the changes between https://github.com/agraef/Gem/commit/53e3be2faf3d7d555ddae8f5d97e14449446b1b0 and current HEAD one by one to see what causes these crashes. Oh well..

**Comment by agraef** [comment]
Ok, I think that we can chalk this up to version differences in libquicktime (and/or avcodec/ffmpeg4). The libquicktime version on openSUSE Tumbleweed is actually much newer (based on the latest Aug 2018 git snapshot), whereas the Arch and Ubuntu packages are based on the tried and proven 1.2.4 release from  2012, with just a handful of selected patches thrown in.

That, and the fact that the multimedia stuff probably doesn't get quite the amount of testing as in the more popular Ubuntu and Arch distros. I guess that they care that vlc, mplayer, and video playback in browsers work, and that's about it. AFAICT, there isn't even a package for pd+gem in this distro, so it's quite clear that they didn't test that either.

I'm going to leave it at that for now -- until we get openSUSE-related bug reports, or until our seminar rooms start being flooded by students running openSUSE Tumbleweed on their laptops. Which IMHO is not very likely to happen any time soon, but you never know. :)

Anyway, I documented this here in such a meticulous detail, so that we know about the problem and how to work around it if needed.

**Comment by umlaeute** [comment]
> he libquicktime version on openSUSE Tumbleweed is actually much newer (based on the latest Aug 2018 git snapshot)

aha. so openSUSE uses an unreleased git-snapshot of some support library, and then *I* get bug-reports... :slightly_frowning_face: 

apart from that: the [libquicktime documentation](http://libquicktime.sourceforge.net/doc/apiref/group__video__decode.html#gae8888a92cc4a27c42d8d323c43a58d62) is pretty explicit that both `track` and `frame` are 0-based (and afaict, your changes boil down to making these params 1-based)

**Pull request closed without merging**
