### PR TITLE
massive additive audio syntesis example

### PR DESCRIPTION
**Pull request by ch-nry**

### CODE REVIEW

**Comment by umlaeute** [comment]
as a side note: you could use `FLOAT` for the data type (in `[gemframebuffer]`, `[pix_snap]` and `[pix_sig2pix~]`).
This way, you do not have to do weird tricks to get more than 8bit audio.

**Comment by ch-nry** [comment]
pix_pix2sig~: no method for 'type'
I still fail getting float value..

**Comment by umlaeute** [comment]
`[pix_pix2sig~]` takes the type from the pix (which can be float, if you tell `[pix_snap]`.

With `[pix_sig2pix~]` you can set the type for the pix domain

**Comment by ch-nry** [comment]
[test_snap_float.zip](https://github.com/user-attachments/files/17137027/test_snap_float.zip)

[pix_snap]: type: GL_FLOAT
[gemframebuffer]: type: FLOAT [5126]

I change the shader, but still : output is only 8 bits.

**Pull request merged**
